# Generated by Django 4.1 on 2023-06-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
