# Generated by Django 4.1 on 2023-06-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_comment_created_at_remove_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='default email', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='default name', max_length=100, verbose_name='name'),
        ),
    ]
